avd list added

diff --git a/.github/workflows/appium_android_tests.yml b/.github/workflows/appium_android_tests.yml
--- a/.github/workflows/appium_android_tests.yml
+++ b/.github/workflows/appium_android_tests.yml
@@ -76,6 +76,15 @@ jobs:
           # Wait for the emulator to initialize
           echo "Waiting 30 seconds for the Android Emulator to start..."
           sleep 30
+          
+      - name: List Available AVDs in Android Emulator Container
+        run: |
+          docker exec $(docker ps -q --filter "ancestor=us-docker.pkg.dev/android-emulator-268719/images/30-google-x64:30.1.2") \
+          avdmanager list avd || echo "avdmanager not found, checking emulator directory instead"
+
+          # If avdmanager is unavailable, fallback to list AVD config files
+          docker exec $(docker ps -q --filter "ancestor=us-docker.pkg.dev/android-emulator-268719/images/30-google-x64:30.1.2") \
+          ls -la $ANDROID_AVD_HOME
 
       - name: Verifying ADB connection
         run: |
