Workflows: manual action added (#67)

diff --git a/.github/workflows/playwright_tests.yml b/.github/workflows/playwright_tests.yml
--- a/.github/workflows/playwright_tests.yml
+++ b/.github/workflows/playwright_tests.yml
@@ -32,6 +32,8 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install tox==3.28.0
+          mkdir -p allure-report
+          chmod -R 777 allure-report
           
       - name: Extract tox env
         run: |
@@ -44,5 +46,21 @@ jobs:
           echo "HOME=/root" >> $GITHUB_ENV  # Set HOME environment variable
 
       - name: Run Playwright ${{ matrix.browser-name }} tests with py${{ matrix.python-version }}
+        id: tests
         run: |
-          tox -e py${{ env.TOX_ENV }}-playwright-${{ matrix.browser-name }} -- --headless -v --sv
+          tox -e py${{ env.TOX_ENV }}-playwright-${{ matrix.browser-name }} -- --headless -v --alluredir=allure-report --reruns=2
+        continue-on-error: true
+
+      - name: Upload Allure Report as Artifact
+        if: steps.tests.outcome == 'failure'
+        uses: actions/upload-artifact@v4
+        with:
+          name: allure-report-${{ matrix.browser-name }}-${{ env.TOX_ENV }}
+          path: allure-report
+          retention-days: 1
+
+      - name: Check Test Results
+        if: steps.tests.outcome == 'failure'
+        run: |
+          echo "❌ Tests failed! Check the Allure Report for details."
+          exit 1 
