Selenium artifacts upload added

diff --git a/.github/workflows/selenium_safari_tests.yml b/.github/workflows/selenium_safari_tests.yml
--- a/.github/workflows/selenium_safari_tests.yml
+++ b/.github/workflows/selenium_safari_tests.yml
@@ -34,5 +34,22 @@ jobs:
           echo "TOX_ENV=${tox_env_variable}" >> $GITHUB_ENV
 
       - name: Run Selenium Safari tests with py${{ matrix.python-version }}
+        id: tests
         run: |
-          tox -e py${{ env.TOX_ENV }}-selenium-safari -- --headless -v -k='not screenshot' --reruns=2
+          tox -e py${{ env.TOX_ENV }}-selenium-safari -- -v
+        continue-on-error: true
+          
+      - name: Upload Allure Report as Artifact
+        if: steps.tests.outcome == 'failure'
+        uses: actions/upload-artifact@v4
+        with:
+          name: allure-report-safari-selenium-${{ env.TOX_ENV }}
+          path: allure-report
+          retention-days: 1
+
+      - name: Check Test Results
+        if: steps.tests.outcome == 'failure'
+        run: |
+          echo "❌ Tests failed! Check the Allure Report for details."
+          exit 1 
+
diff --git a/.github/workflows/selenium_tests.yml b/.github/workflows/selenium_tests.yml
--- a/.github/workflows/selenium_tests.yml
+++ b/.github/workflows/selenium_tests.yml
@@ -48,4 +48,19 @@ jobs:
 
       - name: Run Selenium ${{ env.BROWSER }} tests with py${{ matrix.python-version }}
         run: |
-          tox -e py${{ env.TOX_ENV }}-selenium-${{ env.BROWSER }} -- --env remote --headless -v --reruns=2
+          tox -e py${{ env.TOX_ENV }}-selenium-${{ env.BROWSER }} -- --env remote --headless -v
+        continue-on-error: true
+
+      - name: Upload Allure Report as Artifact
+        if: steps.tests.outcome == 'failure'
+        uses: actions/upload-artifact@v4
+        with:
+          name: allure-report-${{ matrix.browser-name }}-selenium-${{ env.TOX_ENV }}
+          path: allure-report
+          retention-days: 1
+
+      - name: Check Test Results
+        if: steps.tests.outcome == 'failure'
+        run: |
+          echo "❌ Tests failed! Check the Allure Report for details."
+          exit 1 
