Workflows: Allure fix

diff --git a/.github/workflows/selenium_chrome_tests.yml b/.github/workflows/selenium_chrome_tests.yml
--- a/.github/workflows/selenium_chrome_tests.yml
+++ b/.github/workflows/selenium_chrome_tests.yml
@@ -48,6 +48,12 @@ jobs:
           tox -e py38-selenium-chrome -- --env remote --headless -v --alluredir=allure-results -k test_screenshot_remove
         continue-on-error: true
 
+      - name: Check Test Results
+        if: steps.selenium_tests.outcome == 'failure'
+        run: |
+          echo "❌ Tests failed! Check the Allure Report for details."
+          exit 1 
+
       - name: Generate Allure Report using Docker
         run: |
           docker run --rm \
@@ -57,17 +63,10 @@ jobs:
             allure generate /allure-results -o /allure-report --clean
           
       - name: Deploy Allure Report to GitHub Pages
-        if: github.ref == 'refs/heads/main'
         uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: allure-report
-
-      - name: Check Test Results
-        if: steps.selenium_tests.outcome == 'failure'
-        run: |
-          echo "❌ Tests failed! Check the Allure Report for details."
-          exit 1
           
       - name: Upload Allure Report as Artifact
         if: always()
